package harkka;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.18 21:03:37 // Generated by ComTest
 *
 */
public class AinesosaTest {



  // Generated by ComTest BEGIN
  /** testParse89 */
  @Test
  public void testParse89() {    // Ainesosa: 89
    Ainesosa a1 = new Ainesosa(); 		a1.rekisteroi(); 		a1.testiarvot(); 
    String s = a1.toString(); 
    Ainesosa a2 = new Ainesosa(); 
    a2.parse(s); 
    a2.getAinesosa().equals(a1.getAinesosa()); assertEquals("From: Ainesosa line: 94", a1.getNimiId(), a2.getNimiId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi108 */
  @Test
  public void testRekisteroi108() {    // Ainesosa: 108
    Ainesosa a1 = new Ainesosa(); 		Ainesosa a2 = new Ainesosa(); 
    int eka = a1.rekisteroi(); 
    assertEquals("From: Ainesosa line: 111", (eka + 1), a2.rekisteroi()); 
  } // Generated by ComTest END
}