package harkka;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.18 21:35:02 // Generated by ComTest
 *
 */
public class AinesosatTest {



  // Generated by ComTest BEGIN
  /** testLisaaAinesosa31 */
  @Test
  public void testLisaaAinesosa31() {    // Ainesosat: 31
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa a1 = new Ainesosa(1); 		Ainesosa a2 = new Ainesosa(2); 
    a1.testiarvot(); 						a2.testiarvot(); 
    ainesosat.lisaaAinesosa(a1); 			ainesosat.lisaaAinesosa(a2); 
    assertEquals("From: Ainesosat line: 36", 2, ainesosat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaAinesosat49 
   * @throws alkioException when error
   */
  @Test
  public void testPoistaAinesosat49() throws alkioException {    // Ainesosat: 49
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa a1 = new Ainesosa(1); 		Ainesosa a2 = new Ainesosa(1); 		Ainesosa a3 = new Ainesosa(2); 
    ainesosat.lisaaAinesosa(a1); 			ainesosat.lisaaAinesosa(a2); 		ainesosat.lisaaAinesosa(a3); 
    assertEquals("From: Ainesosat line: 55", true, ainesosat.poistaAinesosat(2)); 
    assertEquals("From: Ainesosat line: 56", 2, ainesosat.getLkm()); 
    assertEquals("From: Ainesosat line: 57", false, ainesosat.poistaAinesosat(7)); 
    assertEquals("From: Ainesosat line: 58", true, ainesosat.poistaAinesosat(1)); 
    assertEquals("From: Ainesosat line: 59", 0, ainesosat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi81 
   * @throws alkioException when error
   */
  @Test
  public void testEtsi81() throws alkioException {    // Ainesosat: 81
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa a1 = new Ainesosa(1); 			Ainesosa a2 = new Ainesosa(2); 
    Ainesosa a3 = new Ainesosa(1); 			Ainesosa a4 = new Ainesosa(3); 
    a1.setAinesosa("300g Kana"); 			a2.setAinesosa("400g Jauheliha"); 
    a3.setAinesosa("Kanaa"); 				a4.setAinesosa("Vesi"); 
    ainesosat.lisaaAinesosa(a1); 		ainesosat.lisaaAinesosa(a2); 		ainesosat.lisaaAinesosa(a3); 		ainesosat.lisaaAinesosa(a4); 
    List<Integer> tulokset = ainesosat.etsi("*kan*"); 
    assertEquals("From: Ainesosat line: 92", 1, tulokset.size()); 
    List<Integer> tulokset2 = ainesosat.etsi("*a*"); 
    assertEquals("From: Ainesosat line: 94", 2, tulokset2.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm114 */
  @Test
  public void testGetLkm114() {    // Ainesosat: 114
    Ainesosat ainesosat = new Ainesosat(); 
    assertEquals("From: Ainesosat line: 116", 0, ainesosat.getLkm()); 
    Ainesosa ao1 = new Ainesosa(); 					Ainesosa ao2 = new Ainesosa(); 
    ainesosat.lisaaAinesosa(ao1); 					ainesosat.lisaaAinesosa(ao2); 
    assertEquals("From: Ainesosat line: 119", 2, ainesosat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaalleKirjoita164 */
  @Test
  public void testPaalleKirjoita164() {    // Ainesosat: 164
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa a1 = new Ainesosa(2); 		Ainesosa a2 = new Ainesosa(1); 		Ainesosa a3 = new Ainesosa(1); 
    a1.testiarvot(); 						a2.testiarvot(); 					a3.testiarvot(); 
    ainesosat.lisaaAinesosa(a1); 			ainesosat.lisaaAinesosa(a2); 		ainesosat.lisaaAinesosa(a3); 
    String uusiTeksti = "Hampurilainen 1kpl"; 
    String[] uusiSplit = uusiTeksti.split(" "); 
    ainesosat.paalleKirjoita(1, 1, uusiSplit); 
    Ainesosa muokattu = ainesosat.annaAinesosa(2); 
    String maara = muokattu.getMaara(); 
    assertEquals("From: Ainesosat line: 176", true, maara.equals("1kpl")); 
    assertEquals("From: Ainesosat line: 177", true, muokattu.getAinesosa().equals("Hampurilainen")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaAinesosa208 */
  @Test
  public void testAnnaAinesosa208() {    // Ainesosat: 208
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa a1 = new Ainesosa(1); 		Ainesosa a2 = new Ainesosa(2); 		Ainesosa a3 = new Ainesosa(3); 
    ainesosat.lisaaAinesosa(a1); 			ainesosat.lisaaAinesosa(a2); 		ainesosat.lisaaAinesosa(a3); 
    assertEquals("From: Ainesosat line: 213", 3, ainesosat.annaAinesosa(2).getNimiId()); 
    assertEquals("From: Ainesosat line: 214", 1, ainesosat.annaAinesosa(0).getNimiId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaAinesosat231 */
  @Test
  public void testAnnaAinesosat231() {    // Ainesosat: 231
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa a1 = new Ainesosa(1); 
    Ainesosa a2 = new Ainesosa(1); 
    Ainesosa a3 = new Ainesosa(2); 
    ainesosat.lisaaAinesosa(a1); 		ainesosat.lisaaAinesosa(a2); 		ainesosat.lisaaAinesosa(a3); 
    List<Ainesosa> tulos1; 
    List<Ainesosa> tulos2; 
    tulos1 = ainesosat.annaAinesosat(1); 
    tulos2 = ainesosat.annaAinesosat(2); 
    assertEquals("From: Ainesosat line: 245", 2, tulos1.size()); 
    assertEquals("From: Ainesosat line: 246", 1, tulos2.size()); 
  } // Generated by ComTest END
}